# Default, Defaults
# markdown: redcarpet
highlighter: rouge # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]

# Jekyll Defaults
title: RR
# email: your-email@domain.com
description: lorem

#GitHub Project Pages Settings
url: "https://ria-rivera.github.io/blog/"
baseurl: "/blog"
url-pretty: "ria-rivera.github.io/blog/"

# Socail Media links
# Use these to link users to your organization's social media sites
twitter:
facebook:
google:

author: RR
authorBio: lorem.
